#!/usr/bin/env bash
# bash script that displays records of subdomains and domains

show_records()
{
	#define arguments  of domains and subdomains 
	domain="$1"
	subdomain="$2"
`	dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    	if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    	then
		show_records "$1" "$subdomain"
    	fi
done
