#!/usr/bin/env bash
# bash script that displays records of subdomains and domains

show_records()
{
	#define arguments  of domains and subdomains 
	domain="$1"
	subdomain="$2"
	dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

if [ "$#" == 1 ]
then
  show_records "$1" "www"
  show_records  "$1" "lb-01"
  show_records "$1" "web-01"
  show_records "$1" "web-02"
elif [ "$#" == 2 ]
then
  show_records "$1" "$2"
