#!/usr/bin/env bash
# bash script that displays records of subdomains and domains

show_records()
{
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  show_records "$1" "www"
  show_records "$1" "lb-01"
  show_records "$1" "web-01"
  show_records "$1" "web-02"
elif [ "$#" == 2 ]
then
  show_records "$1" "$2"
fi
